version: '3.9'

networks:
  global-docker-net:
    external: true
  
services:
  dotnet:
    build: ./dotnet 
    container_name: onquete-api-app
    ports:
      - 5500:5500
    command: dotnet restore && dotnet watch
    volumes:
      - ../:/app
    networks:
      - global-docker-net

  db:
    image: mysql:latest
    container_name: onquete-api-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=onquete
    networks:
      - global-docker-net