version: '3.9'

volumes:
  database-onquete-api-app:
networks:
  global-docker-net:
    external: true
  
services:
  onquete-api-app:
    build: 
      dockerfile: ./.docker/dotnet/Dockerfile
      context: ../
    container_name: onquete-api-app
    ports:
      - 5500:5500
      - 7057:7057
    volumes:
      - ../:/app
    command:
      - "watch"
    networks:
      - global-docker-net

  db:
    image: mysql:latest
    container_name: onquete-api-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - database-onquete-api-app:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=onquete
    networks:
      - global-docker-net